# Generated by Django 5.1.7 on 2025-03-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('telephone', models.CharField(max_length=20)),
                ('photo', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vétérinaire',
                'verbose_name_plural': 'Vétérinaires',
            },
        ),
    ]
